spring:

  liquibase:
    enabled: true
    change-log: db/changelog/postgre/pg.changelog-master.xml

  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:8081/menu-voter
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  test:
    database:
      replace: none
