spring:
  data:
    mongodb:
      database: menu
      uri: mongodb://user:password@localhost:8082/menu?authSource=admin

  liquibase:
    enabled: true
    change-log: db/changelog/postgre/pg.changelog-master.xml

  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:8081/menu-voter
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    generate-ddl: false

  test:
    database:
      replace: none

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true